### ISSUE TITLE
potential future problem -- keep wait_for_ssh?

### ISSUE THREAD

**Issue by thoraxe** [sborenst/ansible_agnostic_deployer#11]
I'm not sure that this works currently as we think it does.

I'd have to double check with -vvv to see if the SSH is being forced through the proxy. If it's trying to make a direct connection to the inventory hosts then that would work for me but potentially would fail in other environments where only the bastion host has SSH open...

**Comment by fridim** [comment]
SSH config file is generated, and bastion is used as a jumb host to reach other hosts (via their private IP).
At least for ec2.
