### ISSUE TITLE
scripts folder unneeded?

### ISSUE THREAD

**Issue by thoraxe** [sborenst/ansible_agnostic_deployer#16]
The inventory script exists in inventory (where it is actively used) and in scripts.

I think we can delete the scripts folder?

**Comment by fridim** [comment]
We do not use inventory scripts anymore, but rather `add_host` in the infra steps depending on tags.

TODO: delete the scripts if we do not use them

**Comment by fridim** [comment]
`scripts` dir containing inventory files has been archived.
