### ISSUE TITLE
[RFE] clarification of the host-ocp-installer tasks

### ISSUE THREAD

**Issue by thoraxe** [sborenst/ansible_agnostic_deployer#164]
https://github.com/sborenst/ansible_agnostic_deployer/blob/development/ansible/roles/host-ocp-installer/tasks/main.yml#L60-L78

This says the same thing twice. If would be more clear if we added something to the task `name` that suggests one is when using the cloned repo, and the other is using the packaged installer.

**Comment by wkulhanek** [comment]
Fixed in commit 025d7fa7df46ea29efb816c9ec321cc3de272cca
