### ISSUE TITLE
Development services in RHPDS based on AAD should have a parameter for a branch

### ISSUE THREAD

**Issue by ericzolf** [sborenst/ansible_agnostic_deployer#187]
Currently, you can't really test a change before you've pushed it to the development branch, meaning that everybody and all services in development are potentially impacted until the issue is fixed.

If development services would have a parameter in which you could enter the name of your development branch, you could order your service so that it is provisioned based on this branch and nobody but you would be impacted if something is wrong.

**Comment by wkulhanek** [comment]
Our workflow is a bit different. We use tags to identify test and prod snapshots of the repo. It's ok to break dev... Once the dev item succeeds we tag the repo with a test tag, run the test item in CF and when that succeeds we tag is as prod. This way we can push to dev without breaking anything in our prod environments.

**Comment by sborenst** [comment]
Yes, externals with no EC2 accounts is something we need to work on.

We will discuss

**Comment by fridim** [comment]
@ericzolf FYI, the branch feature (or PR number) is something we want to implement for DEV catalog items.
It would be a free field in CloudForms for the user to provide. Or, if CloudForms can do it, fetch the list of PRs and provide it in a scrolling list, so user just have to pick one.

It's more on the side of  CloudForms and OPEN_Admin provisioning scripts, not really an AAD per-se issue.
