### ISSUE TITLE
[bu-workshop] add gluster CNS

### ISSUE THREAD

**Issue by thoraxe** [sborenst/ansible_agnostic_deployer#19]

**Comment by sborenst** [comment]
Let's do that when version 3.6 comes out.

**Comment by siamaksade** [comment]
Time to revisit? :)

**Comment by fridim** [comment]
FYI we got one working for ocp-workshop and 3.7

**Comment by fridim** [comment]
It's possible to install CNS since 3.7 in ocp-workshop. I'm closing this issue, feel free to re-open.
