### ISSUE TITLE
switch to file-based SSH config implementation

### ISSUE THREAD

**Issue by thoraxe** [sborenst/ansible_agnostic_deployer#35]
We ran into an issue with SSH and quoting and etc. when testing the bu-workshop playbooks in the OpenTLC environment. I believe that switching "back" to the file-based SSH config implementation may resolve those SSH issues.

I was doing this here, but it somehow did not make it into the current master:

https://github.com/thoraxe/ansible_agnostic_deployer/blob/cns/ansible/main.yml#L43-L76

Then, the ssh_vars file simply has:

```yaml
ansible_ssh_extra_args: "-F /tmp/{{ env_type }}_{{ guid }}_ssh_conf"
```

Although I believe you wanted the file in "workdir".

The one caveat is that the cleanup should be amended to delete this ssh config as well (make sure the file is absent).

**Comment by fridim** [comment]
that's how we do it today. Closing.
