### ISSUE TITLE
common role should be split to subs, repos, and then common setup

### ISSUE THREAD

**Issue by thoraxe** [sborenst/ansible_agnostic_deployer#5]
Ansible with subscription manager is really finicky. As such it would be nice to run those steps in serial. However, with the current common role, if run in serial it takes an extremely long time because both update and install of packages are included.

I think it would be cleaner if we had a subs role, a repos role, and a common role:

subs - use subscription manager to register and attach systems (ignored in some cases)
repos - use either yum repo config or subscription manager to configure repos (depending on config)
common - install common packages and potentially apply updates

This would allow the "subs" role to be serialized to improve performance, and then the other two roles could remain in parallel.

Thoughts?

**Comment by vvaldez** [comment]
Feel free to repurpose the Subscription Manager role I wrote for the CASL project: https://github.com/redhat-cop/casl-ansible/tree/master/roles/subscription-manager
